"""Add missing user fields

Revision ID: 933168ce660f
Revises: 
Create Date: 2025-07-28 16:53:57.446826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '933168ce660f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BIGINT(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('matched_records', sa.Integer(), nullable=True),
    sa.Column('error_records', sa.Integer(), nullable=True),
    sa.Column('similarity_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processing_started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processing_finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detected_encoding', sa.String(length=50), nullable=True),
    sa.Column('detected_delimiter', sa.String(length=10), nullable=True),
    sa.Column('sheet_names', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('processed_sheet', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_content_hash'), 'files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_files_file_type'), 'files', ['file_type'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_processing_status'), 'files', ['processing_status'], unique=False)
    op.create_index(op.f('ix_files_uploaded_at'), 'files', ['uploaded_at'], unique=False)
    op.create_table('unified_orders',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_number', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('machine_code', sa.String(length=50), nullable=True),
    sa.Column('goods_name', sa.String(length=255), nullable=True),
    sa.Column('taste_name', sa.String(length=255), nullable=True),
    sa.Column('order_type', sa.String(length=100), nullable=True),
    sa.Column('order_resource', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('brew_status', sa.String(length=50), nullable=True),
    sa.Column('order_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('creation_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('paying_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('brewing_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('delivery_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('refund_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('vhr_id', sa.Integer(), nullable=True),
    sa.Column('vhr_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('vhr_ikpu_code', sa.String(length=50), nullable=True),
    sa.Column('vhr_barcode', sa.String(length=100), nullable=True),
    sa.Column('vhr_marking', sa.String(length=100), nullable=True),
    sa.Column('vhr_payment_type', sa.String(length=100), nullable=True),
    sa.Column('vhr_username', sa.String(length=255), nullable=True),
    sa.Column('vhr_accrued_bonus', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('vhr_machine_category', sa.String(length=255), nullable=True),
    sa.Column('fiscal_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('fiscal_module', sa.String(length=100), nullable=True),
    sa.Column('fiscal_recipe_number', sa.String(length=50), nullable=True),
    sa.Column('fiscal_operation_type', sa.String(length=50), nullable=True),
    sa.Column('fiscal_cashier', sa.String(length=255), nullable=True),
    sa.Column('fiscal_trade_point', sa.String(length=255), nullable=True),
    sa.Column('fiscal_operation_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('fiscal_cash_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('fiscal_card_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('fiscal_customer_info', sa.Text(), nullable=True),
    sa.Column('fiscal_operation_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('payme_provider_name', sa.String(length=100), nullable=True),
    sa.Column('payme_cashbox_name', sa.String(length=255), nullable=True),
    sa.Column('payme_payment_state', sa.String(length=50), nullable=True),
    sa.Column('payme_payment_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('payme_processing_name', sa.String(length=100), nullable=True),
    sa.Column('payme_card_number', sa.String(length=50), nullable=True),
    sa.Column('payme_amount_without_commission', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('payme_client_commission', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('payme_payment_system_id', sa.String(length=255), nullable=True),
    sa.Column('payme_provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('payme_rrn', sa.String(length=50), nullable=True),
    sa.Column('payme_fiscal_receipt_id', sa.String(length=50), nullable=True),
    sa.Column('payme_order_number', sa.String(length=50), nullable=True),
    sa.Column('click_id', sa.String(length=50), nullable=True),
    sa.Column('click_billing_id', sa.String(length=50), nullable=True),
    sa.Column('click_identifier', sa.String(length=50), nullable=True),
    sa.Column('click_service_name', sa.String(length=100), nullable=True),
    sa.Column('click_client_info', sa.String(length=100), nullable=True),
    sa.Column('click_payment_method', sa.String(length=100), nullable=True),
    sa.Column('click_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('click_payment_status', sa.String(length=50), nullable=True),
    sa.Column('click_cashbox', sa.String(length=100), nullable=True),
    sa.Column('click_payment_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('uzum_service_name', sa.String(length=255), nullable=True),
    sa.Column('uzum_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('uzum_commission', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('uzum_card_type', sa.String(length=50), nullable=True),
    sa.Column('uzum_card_number', sa.String(length=50), nullable=True),
    sa.Column('uzum_status', sa.String(length=50), nullable=True),
    sa.Column('uzum_merchant_id', sa.String(length=50), nullable=True),
    sa.Column('uzum_receipt_id', sa.String(length=255), nullable=True),
    sa.Column('uzum_parsed_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=True),
    sa.Column('source_files', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_matched_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unified_orders_creation_time'), 'unified_orders', ['creation_time'], unique=False)
    op.create_index(op.f('ix_unified_orders_id'), 'unified_orders', ['id'], unique=False)
    op.create_index(op.f('ix_unified_orders_is_temporary'), 'unified_orders', ['is_temporary'], unique=False)
    op.create_index(op.f('ix_unified_orders_machine_code'), 'unified_orders', ['machine_code'], unique=False)
    op.create_index(op.f('ix_unified_orders_match_score'), 'unified_orders', ['match_score'], unique=False)
    op.create_index(op.f('ix_unified_orders_order_number'), 'unified_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_unified_orders_order_price'), 'unified_orders', ['order_price'], unique=False)
    op.create_table('click_payments',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('click_id', sa.String(length=50), nullable=False),
    sa.Column('billing_id', sa.String(length=50), nullable=True),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('client_info', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('cashbox', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_payments_amount'), 'click_payments', ['amount'], unique=False)
    op.create_index(op.f('ix_click_payments_billing_id'), 'click_payments', ['billing_id'], unique=False)
    op.create_index(op.f('ix_click_payments_click_id'), 'click_payments', ['click_id'], unique=True)
    op.create_index(op.f('ix_click_payments_id'), 'click_payments', ['id'], unique=False)
    op.create_index(op.f('ix_click_payments_payment_date'), 'click_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_click_payments_payment_status'), 'click_payments', ['payment_status'], unique=False)
    op.create_table('fiscal_receipts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('fiscal_module', sa.String(length=100), nullable=True),
    sa.Column('recipe_number', sa.String(length=50), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=True),
    sa.Column('cashier', sa.String(length=255), nullable=True),
    sa.Column('trade_point', sa.String(length=255), nullable=True),
    sa.Column('operation_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('cash_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('card_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('customer_info', sa.Text(), nullable=True),
    sa.Column('operation_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_receipts_cash_amount'), 'fiscal_receipts', ['cash_amount'], unique=False)
    op.create_index(op.f('ix_fiscal_receipts_fiscal_module'), 'fiscal_receipts', ['fiscal_module'], unique=False)
    op.create_index(op.f('ix_fiscal_receipts_id'), 'fiscal_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_fiscal_receipts_operation_datetime'), 'fiscal_receipts', ['operation_datetime'], unique=False)
    op.create_index(op.f('ix_fiscal_receipts_receipt_number'), 'fiscal_receipts', ['receipt_number'], unique=False)
    op.create_index(op.f('ix_fiscal_receipts_trade_point'), 'fiscal_receipts', ['trade_point'], unique=False)
    op.create_table('hardware_orders',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_number', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('machine_code', sa.String(length=50), nullable=True),
    sa.Column('goods_name', sa.String(length=255), nullable=True),
    sa.Column('taste_name', sa.String(length=255), nullable=True),
    sa.Column('order_type', sa.String(length=100), nullable=True),
    sa.Column('order_resource', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('brew_status', sa.String(length=50), nullable=True),
    sa.Column('order_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('creation_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('paying_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('brewing_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('delivery_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('refund_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_orders_brew_status'), 'hardware_orders', ['brew_status'], unique=False)
    op.create_index(op.f('ix_hardware_orders_creation_time'), 'hardware_orders', ['creation_time'], unique=False)
    op.create_index(op.f('ix_hardware_orders_id'), 'hardware_orders', ['id'], unique=False)
    op.create_index(op.f('ix_hardware_orders_machine_code'), 'hardware_orders', ['machine_code'], unique=False)
    op.create_index(op.f('ix_hardware_orders_order_number'), 'hardware_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_hardware_orders_payment_status'), 'hardware_orders', ['payment_status'], unique=False)
    op.create_table('order_errors',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_number', sa.String(length=255), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.Column('source_record_id', sa.BIGINT(), nullable=True),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('target_record_id', sa.BIGINT(), nullable=True),
    sa.Column('conflicting_values', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('suggested_resolution', sa.Text(), nullable=True),
    sa.Column('error_timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('processing_batch_id', sa.UUID(), nullable=True),
    sa.Column('resolution_status', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_errors_error_timestamp'), 'order_errors', ['error_timestamp'], unique=False)
    op.create_index(op.f('ix_order_errors_error_type'), 'order_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_order_errors_id'), 'order_errors', ['id'], unique=False)
    op.create_index(op.f('ix_order_errors_order_number'), 'order_errors', ['order_number'], unique=False)
    op.create_index(op.f('ix_order_errors_resolution_status'), 'order_errors', ['resolution_status'], unique=False)
    op.create_index(op.f('ix_order_errors_severity'), 'order_errors', ['severity'], unique=False)
    op.create_table('payme_payments',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('report_number', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('cashbox_name', sa.String(length=255), nullable=True),
    sa.Column('payment_state', sa.String(length=50), nullable=True),
    sa.Column('payment_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('cancel_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('processing_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('bank_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('processing_name', sa.String(length=100), nullable=True),
    sa.Column('epos_merchant_id', sa.String(length=50), nullable=True),
    sa.Column('epos_terminal_id', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.Column('amount_without_commission', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('client_commission', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('payment_system_id', sa.String(length=255), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('rrn', sa.String(length=50), nullable=True),
    sa.Column('cashbox_identifier', sa.String(length=255), nullable=True),
    sa.Column('cash_register_id', sa.String(length=255), nullable=True),
    sa.Column('bank_receipt_date', sa.Date(), nullable=True),
    sa.Column('fiscal_sign', sa.String(length=50), nullable=True),
    sa.Column('fiscal_receipt_id', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('payment_description', sa.Text(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payme_payments_amount_without_commission'), 'payme_payments', ['amount_without_commission'], unique=False)
    op.create_index(op.f('ix_payme_payments_cashbox_name'), 'payme_payments', ['cashbox_name'], unique=False)
    op.create_index(op.f('ix_payme_payments_id'), 'payme_payments', ['id'], unique=False)
    op.create_index(op.f('ix_payme_payments_order_number'), 'payme_payments', ['order_number'], unique=False)
    op.create_index(op.f('ix_payme_payments_payment_system_id'), 'payme_payments', ['payment_system_id'], unique=False)
    op.create_index(op.f('ix_payme_payments_payment_time'), 'payme_payments', ['payment_time'], unique=False)
    op.create_index(op.f('ix_payme_payments_processing_name'), 'payme_payments', ['processing_name'], unique=False)
    op.create_table('sales_reports',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=255), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.Column('time_value', sa.DECIMAL(precision=20, scale=10), nullable=True),
    sa.Column('formatted_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('goods_name', sa.String(length=255), nullable=True),
    sa.Column('order_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('ikpu_code', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('marking', sa.String(length=100), nullable=True),
    sa.Column('order_resource', sa.String(length=100), nullable=True),
    sa.Column('payment_type', sa.String(length=100), nullable=True),
    sa.Column('machine_category', sa.String(length=255), nullable=True),
    sa.Column('machine_code', sa.String(length=50), nullable=True),
    sa.Column('accrued_bonus', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_reports_formatted_time'), 'sales_reports', ['formatted_time'], unique=False)
    op.create_index(op.f('ix_sales_reports_goods_name'), 'sales_reports', ['goods_name'], unique=False)
    op.create_index(op.f('ix_sales_reports_id'), 'sales_reports', ['id'], unique=False)
    op.create_index(op.f('ix_sales_reports_machine_code'), 'sales_reports', ['machine_code'], unique=False)
    op.create_index(op.f('ix_sales_reports_order_number'), 'sales_reports', ['order_number'], unique=False)
    op.create_index(op.f('ix_sales_reports_payment_type'), 'sales_reports', ['payment_type'], unique=False)
    op.create_table('uzum_payments',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('commission', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('merchant_id', sa.String(length=50), nullable=True),
    sa.Column('receipt_id', sa.String(length=255), nullable=False),
    sa.Column('payment_datetime', sa.String(length=100), nullable=True),
    sa.Column('parsed_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uzum_payments_amount'), 'uzum_payments', ['amount'], unique=False)
    op.create_index(op.f('ix_uzum_payments_id'), 'uzum_payments', ['id'], unique=False)
    op.create_index(op.f('ix_uzum_payments_merchant_id'), 'uzum_payments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_uzum_payments_parsed_datetime'), 'uzum_payments', ['parsed_datetime'], unique=False)
    op.create_index(op.f('ix_uzum_payments_receipt_id'), 'uzum_payments', ['receipt_id'], unique=True)
    op.create_index(op.f('ix_uzum_payments_status'), 'uzum_payments', ['status'], unique=False)
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_creation_time', table_name='orders')
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_index('ix_orders_machine_code', table_name='orders')
    op.drop_index('ix_orders_match_status', table_name='orders')
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.drop_index('ix_orders_payment_type', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_uploaded_files_content_hash', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_id', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.add_column('order_changes', sa.Column('table_name', sa.String(length=50), nullable=False))
    op.add_column('order_changes', sa.Column('record_id', sa.BIGINT(), nullable=False))
    op.add_column('order_changes', sa.Column('order_number', sa.String(length=255), nullable=True))
    op.add_column('order_changes', sa.Column('change_reason', sa.Text(), nullable=True))
    op.add_column('order_changes', sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True))
    op.add_column('order_changes', sa.Column('processing_batch_id', sa.UUID(), nullable=True))
    op.add_column('order_changes', sa.Column('validation_status', sa.String(length=50), nullable=True))
    op.alter_column('order_changes', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_order_changes_field_name', table_name='order_changes')
    op.drop_index('ix_order_changes_order_id', table_name='order_changes')
    op.create_index(op.f('ix_order_changes_change_type'), 'order_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_order_changes_order_number'), 'order_changes', ['order_number'], unique=False)
    # Удаляем внешние ключи с правильными именами
    try:
        op.drop_constraint('order_changes_order_id_fkey', 'order_changes', type_='foreignkey')
    except:
        pass
    try:
        op.drop_constraint('order_changes_source_file_id_fkey', 'order_changes', type_='foreignkey')
    except:
        pass
    try:
        op.drop_constraint('order_changes_changed_by_fkey', 'order_changes', type_='foreignkey')
    except:
        pass
    op.create_foreign_key(None, 'order_changes', 'files', ['source_file_id'], ['id'])
    op.drop_column('order_changes', 'version')
    op.drop_column('order_changes', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_changes', sa.Column('order_id', sa.INTEGER(), nullable=False))
    op.add_column('order_changes', sa.Column('version', sa.INTEGER(), nullable=False))
    # Удаляем внешний ключ с правильным именем
    try:
        op.drop_constraint('order_changes_source_file_id_fkey', 'order_changes', type_='foreignkey')
    except:
        pass
    op.create_foreign_key(None, 'order_changes', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_changes', 'uploaded_files', ['source_file_id'], ['id'])
    op.create_foreign_key(None, 'order_changes', 'users', ['changed_by'], ['id'])
    op.drop_index(op.f('ix_order_changes_order_number'), table_name='order_changes')
    op.drop_index(op.f('ix_order_changes_change_type'), table_name='order_changes')
    op.create_index('ix_order_changes_order_id', 'order_changes', ['order_id'], unique=False)
    op.create_index('ix_order_changes_field_name', 'order_changes', ['field_name'], unique=False)
    op.alter_column('order_changes', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('order_changes', 'validation_status')
    op.drop_column('order_changes', 'processing_batch_id')
    op.drop_column('order_changes', 'confidence_score')
    op.drop_column('order_changes', 'change_reason')
    op.drop_column('order_changes', 'order_number')
    op.drop_column('order_changes', 'record_id')
    op.drop_column('order_changes', 'table_name')
    op.create_table('uploaded_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('file_size', sa.BIGINT(), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('storage_path', sa.TEXT(), nullable=False),
    sa.Column('similarity_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('similar_file_id', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processed', sa.BOOLEAN(), nullable=True),
    sa.Column('total_rows', sa.INTEGER(), nullable=True),
    sa.Column('new_rows', sa.INTEGER(), nullable=True),
    sa.Column('updated_rows', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['similar_file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_files_id', 'uploaded_files', ['id'], unique=False)
    op.create_index('ix_uploaded_files_content_hash', 'uploaded_files', ['content_hash'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('machine_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('goods_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('taste_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('order_resource', sa.VARCHAR(length=100), nullable=True),
    sa.Column('order_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('creation_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('paying_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('brewing_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('delivery_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('refund_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=100), nullable=True),
    sa.Column('brew_status', sa.VARCHAR(length=100), nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('match_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('source_file_id', sa.INTEGER(), nullable=True),
    sa.Column('additional_data', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_payment_type', 'orders', ['payment_type'], unique=False)
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('ix_orders_match_status', 'orders', ['match_status'], unique=False)
    op.create_index('ix_orders_machine_code', 'orders', ['machine_code'], unique=False)
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.create_index('ix_orders_creation_time', 'orders', ['creation_time'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.drop_index(op.f('ix_uzum_payments_status'), table_name='uzum_payments')
    op.drop_index(op.f('ix_uzum_payments_receipt_id'), table_name='uzum_payments')
    op.drop_index(op.f('ix_uzum_payments_parsed_datetime'), table_name='uzum_payments')
    op.drop_index(op.f('ix_uzum_payments_merchant_id'), table_name='uzum_payments')
    op.drop_index(op.f('ix_uzum_payments_id'), table_name='uzum_payments')
    op.drop_index(op.f('ix_uzum_payments_amount'), table_name='uzum_payments')
    op.drop_table('uzum_payments')
    op.drop_index(op.f('ix_sales_reports_payment_type'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_order_number'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_machine_code'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_id'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_goods_name'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_formatted_time'), table_name='sales_reports')
    op.drop_table('sales_reports')
    op.drop_index(op.f('ix_payme_payments_processing_name'), table_name='payme_payments')
    op.drop_index(op.f('ix_payme_payments_payment_time'), table_name='payme_payments')
    op.drop_index(op.f('ix_payme_payments_payment_system_id'), table_name='payme_payments')
    op.drop_index(op.f('ix_payme_payments_order_number'), table_name='payme_payments')
    op.drop_index(op.f('ix_payme_payments_id'), table_name='payme_payments')
    op.drop_index(op.f('ix_payme_payments_cashbox_name'), table_name='payme_payments')
    op.drop_index(op.f('ix_payme_payments_amount_without_commission'), table_name='payme_payments')
    op.drop_table('payme_payments')
    op.drop_index(op.f('ix_order_errors_severity'), table_name='order_errors')
    op.drop_index(op.f('ix_order_errors_resolution_status'), table_name='order_errors')
    op.drop_index(op.f('ix_order_errors_order_number'), table_name='order_errors')
    op.drop_index(op.f('ix_order_errors_id'), table_name='order_errors')
    op.drop_index(op.f('ix_order_errors_error_type'), table_name='order_errors')
    op.drop_index(op.f('ix_order_errors_error_timestamp'), table_name='order_errors')
    op.drop_table('order_errors')
    op.drop_index(op.f('ix_hardware_orders_payment_status'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_order_number'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_machine_code'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_id'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_creation_time'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_brew_status'), table_name='hardware_orders')
    op.drop_table('hardware_orders')
    op.drop_index(op.f('ix_fiscal_receipts_trade_point'), table_name='fiscal_receipts')
    op.drop_index(op.f('ix_fiscal_receipts_receipt_number'), table_name='fiscal_receipts')
    op.drop_index(op.f('ix_fiscal_receipts_operation_datetime'), table_name='fiscal_receipts')
    op.drop_index(op.f('ix_fiscal_receipts_id'), table_name='fiscal_receipts')
    op.drop_index(op.f('ix_fiscal_receipts_fiscal_module'), table_name='fiscal_receipts')
    op.drop_index(op.f('ix_fiscal_receipts_cash_amount'), table_name='fiscal_receipts')
    op.drop_table('fiscal_receipts')
    op.drop_index(op.f('ix_click_payments_payment_status'), table_name='click_payments')
    op.drop_index(op.f('ix_click_payments_payment_date'), table_name='click_payments')
    op.drop_index(op.f('ix_click_payments_id'), table_name='click_payments')
    op.drop_index(op.f('ix_click_payments_click_id'), table_name='click_payments')
    op.drop_index(op.f('ix_click_payments_billing_id'), table_name='click_payments')
    op.drop_index(op.f('ix_click_payments_amount'), table_name='click_payments')
    op.drop_table('click_payments')
    op.drop_index(op.f('ix_unified_orders_order_price'), table_name='unified_orders')
    op.drop_index(op.f('ix_unified_orders_order_number'), table_name='unified_orders')
    op.drop_index(op.f('ix_unified_orders_match_score'), table_name='unified_orders')
    op.drop_index(op.f('ix_unified_orders_machine_code'), table_name='unified_orders')
    op.drop_index(op.f('ix_unified_orders_is_temporary'), table_name='unified_orders')
    op.drop_index(op.f('ix_unified_orders_id'), table_name='unified_orders')
    op.drop_index(op.f('ix_unified_orders_creation_time'), table_name='unified_orders')
    op.drop_table('unified_orders')
    op.drop_index(op.f('ix_files_uploaded_at'), table_name='files')
    op.drop_index(op.f('ix_files_processing_status'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_type'), table_name='files')
    op.drop_index(op.f('ix_files_content_hash'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
